% Perfil: Redes/Infra e Seguranca
resposta(1, n).
resposta(2, n).
resposta(3, s).
resposta(4, n).
resposta(5, n).
resposta(6, n).
resposta(7, n).
resposta(8, n).
resposta(9, n).
resposta(10, n).
resposta(11, n).
resposta(12, s).
resposta(13, s).
resposta(14, s).
resposta(15, s).
resposta(16, s).
resposta(17, s).
resposta(18, s).
resposta(19, s).
